# Generated by Django 6.0.5 on 2026-05-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField(unique=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.BigIntegerField(unique=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("IT", "IT"),
                            ("SALES", "SALES"),
                            ("HR", "HR"),
                            ("FINANCE", "FINANCE"),
                            ("MARKETING", "MARKETING"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("Python Developer", "Python Developer"),
                            ("Java Developer", "Java Developer"),
                            ("AI Engineer", "AI Engineer"),
                            ("ML Engineer", "ML Engineer"),
                            ("Devops Engineer", "Software Developer"),
                            ("Backend Developer", "Backend Developer"),
                            ("Frontend Developer", "Frontend Developer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("joining_date", models.DateField(auto_now_add=True)),
                ("profile_image", models.ImageField(upload_to="images")),
            ],
        ),
    ]
