# Generated by Django 6.0.5 on 2026-05-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeemodel",
            name="joining_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="employeemodel",
            name="profile_image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
